### PR TITLE
Remove unnecessary to_string conversion

### PR DESCRIPTION
**Pull request by raindev**

### CODE REVIEW

**Comment by chriskrycho** [comment]
:+1:

**Comment by chriskrycho** [comment]
Doesn't compile!

Reminds me: I want to set up a different Travis job for this to check pull requests to make sure all tests still pass and everything still builds.

**Comment by chriskrycho** [comment]
@raindev, as I'm looking at _why_ this doesn't build: it actually needed to convert to a string because the type in the `struct` was a string:

``` rust
pub struct SimpleType {
    a: String,
    b: i32
}
```

For your solution to work, we'd need that underlying type to be `a: &str`, but then we'd need to specify a lifetime:

``` rust
pub struct SimpleType {
    a: &'static str,
    b: i32
}

#[test]
fn test_impl_display() {
    let simple = SimpleType { a: "some string", b: 4096 };
    println!("simple is {}", simple);
}
```

I'm going to go ahead and leave it as is, because I don't want to get into lifetimes yet, and I'm trying for the most part to keep the code samples such that they only include ideas we've talked about so far on the show.

Much obliged, though—not least because it made me solidify my own understanding on how to declare string slices!

**Comment by raindev** [comment]
@chriskrycho I'm really sorry for bothering you with non-compiling pull request. I've messed my local cargo build so were wrongfully thinking that it will work with nightly version of Rust. `cargo build` won't compile tests as it turned out even though the tests are placed in the same source file as the main code.

> I'm trying for the most part to keep the code samples such that they only include ideas we've talked about so far on the show.

That's the right approach, completely agree.

I saw you've set up TravisCI to check status of pull requests - good job :+1:

**Comment by chriskrycho** [comment]
@raindev, no worries! Totally not a problem, and it motivated me to get Travis up and running for pull requests (which I'd never configured myself before), so it ended up working out for the best anyway! :wink:

**Pull request closed without merging**
